name: CI/CD azure-app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'azure-appt'  # Doit correspondre exactement au nom dans Azure
  PYTHON_VERSION: '3.11'           # Version cible (identique à votre pile d'exécution)
  RESOURCE_GROUP: 'WebProjet'      # Groupe de ressources de votre App Service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Étape 1: Récupération du code
    - uses: actions/checkout@v4

    # Étape 2: Configuration Python
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # Étape 3: Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn  # Critique pour le déploiement Azure

    # Étape 4: Création du package (en excluant venv)
    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x 'venv/*' -x '.git/*' -x '.github/*'

    # Étape 5: Déploiement sur Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: deploy.zip
